# Generated by Django 3.1.7 on 2021-03-06 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doencas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50)),
                ('senha', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('crm', models.CharField(max_length=50)),
                ('Login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.login')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Uf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=2)),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('idade', models.SmallIntegerField()),
                ('data_nascimento', models.DateField()),
                ('data_diagnostico', models.DateField()),
                ('nome_mae', models.CharField(max_length=200)),
                ('sexo', models.CharField(max_length=1)),
                ('Doencas_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.doencas')),
                ('Login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.login')),
                ('Medico_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.medico')),
                ('uf_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.uf')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('Uf_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.uf')),
            ],
        ),
        migrations.AddField(
            model_name='login',
            name='Tipo_usuario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.tipo_usuario'),
        ),
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('Login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.login')),
            ],
        ),
    ]
