# Generated by Django 3.1.7 on 2021-03-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_auto_20210306_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='data_diagnostico',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
