# Generated by Django 3.1.7 on 2021-03-06 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_auto_20210306_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='Doencas_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.doencas'),
        ),
    ]
