# Generated by Django 3.1.7 on 2021-03-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_pacientes_municipio_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='descricao_doenca',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
